name: Java 15 CI with Maven
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Build with Maven
      run: |
        mvn -B clean package --file pom.xml
        echo "::set-output name=APP_VERSION::$(mvn --file pom.xml -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)"
      id: build-version
    - name: Save version
      uses: noobly314/share-data@v1
      with:
        share-id: app_version
        mode: set
        key: version
        value: ${{ steps.build-version.outputs.APP_VERSION }}

  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - run: mvn -B verify -P coverage --no-transfer-progress
      - uses: codecov/codecov-action@v1
        with:
          file: ./**/target/site/jacoco/jacoco.xml
          token: ${{ secrets.COVERAGE_SECRET }}
          name: codecov

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Publish package
        run: mvn -B deploy
        env:
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
      - name: Get Version
        id: get-version
        uses: noobly314/share-data@v1
        with:
          share-id: app_version
          mode: get
          key: version
      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: ${{ steps.get-version.outputs.data }}
          token: ${{ secrets.PACKAGE_TOKEN }}